config/routes.rb
Rails.application.routes.draw do

  get 'class/PagesController'

  root :to => "profiles#home"

  get 'archives' => 'profiles#archives', as: :archives
  get 'howtoplay' => 'profiles#howtoplay', as: :howtoplay

  resources :games, only: [:show, :new, :create, :update, :destroy]

  get 'games/:id/play' => 'games#play', as: :play

  put 'games/:id/play_cards' => 'games#play_cards', as: :play_cards

  get 'games/:id/archive' => 'games#archive', as: :archive

  get 'games/:id/field.:format' => 'games#get_game_state', as: :get_game_state

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_many :players

  # increment game play count by 1; also increment win or loss count
  # based on win_loss_result value (:win, :loss, or nil)
  def add_completed_game(win_loss_result = nil)
    self.games_played = games_played.to_i + 1
    if win_loss_result == :win
      self.wins = wins.to_i + 1
    elsif win_loss_result == :loss
      self.losses = losses.to_i + 1
    end
    save
  end

  def name
    user.name if user
  end

  def games
    players.map {|pl| pl.game }
  end

  def games_waiting_to_start
    players.map {|pl| pl.game if pl.game.waiting_to_start? }.compact
  end

  # does at least one active game exist?
  def has_games_waiting_to_start?
    games_waiting_to_start.length > 0
  end

  # does at least one active game exist?
  def has_active_games?
    active_games.length > 0
  end

  # get all active games
  def active_games
    players.map {|pl| pl.game if pl.game.active? }.compact
  end

  # does at least one archived game exist?
  def has_archived_games?
    archived_games.length > 0
  end

  # get all games completed by this player
  def archived_games
    players.map {|pl| pl.game if pl.game.finished? }.compact
  end

  # does player have both active and waiting games?
  def has_games_active_and_waiting_to_start?
    has_games_waiting_to_start? && has_active_games?
  end

  # returns last game completely finished
  def last_finished_game
    archived_games.sort_by {|g| g.finished_at }.last
  end

  # print player's full profile stats
  def full_profile
    "#{name}: #{archived_games.length} games finished."
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  # user dashboard / home page
  def home
    current_user
    @games = @current_profile.games if @current_profile
    respond_to do |format|
      format.html # home.html.erb
      format.json  { render :json => (@current_profile || {}) }
    end
  end

  # page for viewing games
  def archives
    current_user
    respond_to do |format|
      format.html # archives.html.erb
      format.json  { render :json => @games }
    end
  end

  # user dashboard / home page
  def howtoplay
    respond_to do |format|
      format.html # home.html.erb
      format.json  { head :ok }
    end
  end


end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/archives.html.erb
<% if @current_profile.has_archived_games? %>
  <h2>Completed games:</h2>
  <% for game in @current_profile.archived_games %>
    <%= render 'games/sets_selected', :game => game %>
  <% end %>
<% end %>

app/views/profiles/home.html.erb
<% if @current_profile.blank? %>
  <h3>You must log in with your Google+ account before playing Setsolver.</h3>
<% else %>
  <h1><%= "#{@current_profile.name}" %></h1>
  <% if @current_profile.has_games_waiting_to_start? %>
    <h2>Games waiting to start:</h2>
    <% for game in @current_profile.games_waiting_to_start %>
        <p><%= game_desc_as_link(game) %> (<%= game.player_names %>):  <%= game_play_link(game) %></p>
    <% end %>
  <% end %>
  <% if @current_profile.has_active_games? %>
    <h2>Active games:</h2>
    <% for game in @current_profile.active_games %>
        <p><%= game_desc_as_link(game) %> (<%= game.player_names %>):  <%= game_play_link(game) %></p>
    <% end %>
  <% end %>
  <% if @current_profile.has_archived_games? %>
    <h3>You have completed <%= number_noun_desc(@current_profile.archived_games.count, 'game') %>.</h3>
    <h3><%= link_to("Click here", archives_path) %> to view your completed games.</h3>
  <% end %>
  <%= link_to("Create a new game", new_game_path, :class => 'mock-fb-button') %>
<% end %>

<%= link_to("How to play Setsolver", howtoplay_path, :class => 'mock-fb-button')  %>

app/views/profiles/howtoplay.html.erb
<h1>How To Play Setsolver</h1>
Setsolver is a Facebook interactive version of the SET&dagger; card game, where the object of the
game is to find "sets" of three cards with matching characteristics.  Each card has four characteristics:
<ul>
<li><strong>number</strong>: the number of shapes on the card.  Every card will have
    <strong>1</strong>, <strong>2</strong>, or <strong>3</strong> shapes, and multiple shapes will
    always be identical to one another.</li>
<li><strong>shape</strong>: the type of shape displayed on the card.  These shapes will always be
    either <strong>oval</strong>, <strong>diamond</strong>, or <strong>squiggle</strong>.
<li><strong>color</strong>: the color of the shapes (<strong>red</strong>, <strong>green</strong>,
    or <strong>purple</strong>).</li>
<li><strong>shading</strong>: how darkly shaded are the shapes? Shapes can be either
    <strong>outlined</strong>, <strong>filled</strong> solid, or <strong>shaded</strong> with line patterns.</li>
</ul>
<p>Think about normal playing cards -- they have two characteristics (number and suit) and the cards
themselves are made up of every combination of number and suit.  A deck of SET cards similarly has
every combination of the four characteristics above, for a result of 3x3x3x3 (or 81) cards.  Here are a
few examples: </p>

<%= print_example_cards.html_safe %>

<h2>Finding a Set</h2>

<p>Now that you are familiar with the cards, we move on to the object of the game: finding three-card
sets. A collection of three cards is considered a set if <strong>all four of their characteristics are
either all alike or all different</strong>.   Three purple cards would count as "all alike" in its
color characteristic, and if these cards were one red, one green, and one purple this would count as
"all different".  If all three other characteristics (number, shading, and shape) fit this patterns
then you have a Set.  If one characteristic fails in being all different or all the same (such as
two purples and a green) then you don't have a Set, regardless of the other three characteristics.</p>

<h2>Examples of Sets</h2>

<h3>Here are some examples of three-card combinations that are Sets:</h3>

<p><%= render_threecard_set_from_cardface_ids(4,31,58).html_safe %>: This is a Set because the colors are
all green, the shadings are all filled, the shapes are all diamonds, but the numbers are all
different (1 diamond, 2 diamond, and 3 diamonds).  Sets like this with three common
characteristics are the easiest to find.</p>

<p><%= render_threecard_set_from_cardface_ids(12,13,17).html_safe %>: This is a Set because the colors are
all red, only one shape exists in each card, and yet the shadings and shapes are all different
for each card.</p>

<p><%= render_threecard_set_from_cardface_ids(2,40,81).html_safe %>: This Set is hard to identify because no
characteristics are alike in any of the cards, but nevertheless it is a Set.  If no obvious Sets
can be found at first, there's a good chance that a three-card Set exists with different colors,
different numbers, different shapes, and different shadings.</p>

<h3>...and here are some three-card examples of non-Sets:</h3>

<p><%= render_threecard_set_from_cardface_ids(4,32,58).html_safe %>: This may look like a Set at first glance
because of the similarity to the first example above.  However, the shapes are not all same or all
different (diamond, squiggle, diamond), and as such this is not a Set.</p>

<p><%= render_threecard_set_from_cardface_ids(65,60,73).html_safe %>: Another deceptive non-Set: the numbers
and colors match up, but the shadings do not. (2 shaded, 1 filled).</p>

<%= link_to("Back to home", root_path, :class => 'mock-fb-button')  %>