config/routes.rb
Rails.application.routes.draw do

  get 'class/PagesController'

  root :to => "profiles#home"

  get 'archives' => 'profiles#archives', as: :archives
  get 'howtoplay' => 'profiles#howtoplay', as: :howtoplay

  resources :games, only: [:show, :new, :create, :update, :destroy]

  get 'games/:id/play' => 'games#play', as: :play

  put 'games/:id/play_cards' => 'games#play_cards', as: :play_cards

  get 'games/:id/archive' => 'games#archive', as: :archive

  get 'games/:id/field.:format' => 'games#get_game_state', as: :get_game_state

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_one :deck
  has_many :players

  after_create :new_deck

  FieldSize = 12
  NumberOfDisplayedRows = 3
  MaxPlayers = 4
  ActivityLogSize = 4
  SetboardColWidth = 84

  MaxSecondsToFindSet = 300

  # each_cmb3 (Class method)
  # performs a ( len 3 ) statistical combination, where len is the length of the
  # in-play deck.  The combination is returned as an array-of-arrays, where the inner
  # arrays are composed of 3 SORTED integers and the outer array has
  # (len)! / ((len-3)! * 3!) elements -- which gets big very quickly for large "len" values.
  def self.each_cmb3( cmb_len )
    retval = []
    # outermost loop: i = iterate from 0 to (len-1), add i to end of all arrays
    # middle loop: j = iterate from (i+1) to (len-1), add j to middle of arrays
    # inner loop: create array with numbers (j+1) to (len-1), which may be empty.
    0.upto(cmb_len - 1) do |i|
      (i+1).upto(cmb_len - 1) do |j|
        k_arr = ((j+1)..(cmb_len - 1)).to_a
        retval += k_arr.map {|k| [i,j,k] }
      end
    end
    retval
  end

  # simple game name, in title form
  def title
    "\##{id}: \"#{name}\""
  end

  # game name, in quick-listing form
  def listing
    "[\##{id}] \"#{name}\""
  end

  def cards_remaining
    deck.facedown.length if deck
  end

  # create new deck with full set of cards, and shuffle cards
  # if auto-shuffle parameter is set
  def new_deck
    if deck
      save
    else
      self.deck = Deck.new
      save && deck.shuffle
    end
  end

  # start playing the game
  def start
    return false if started?
    self.started_at = Time.now
    self.paused_at = nil
    self.resumed_at = nil
    self.finished_at = nil
    self.save
  end

  def flat_field
    deck.gamefield
  end

  # get current gamefield as 2-dimensional array, where each
  # top-level array element is a row of cards.  If gamefield cards are notice
  # equally distributed among each row, then topmost rows will fill up and
  # the bottom row will contain the remainder of the cards.
  def field
    gamefield = flat_field
    row_length = (gamefield.count.to_f / NumberOfDisplayedRows).ceil;
    (1..NumberOfDisplayedRows).map { gamefield.slice!(0, row_length) }
  end

  # return game status in human-readable form
  def status
    return 'active' if active?
    return 'finished' if finished?
    return 'waiting'
  end

  # return score corresponding to player passed in
  def score( plyr )
    plyr.score
  end

  # has game been started?  Games musst have at least one player and a start date to be considered started.
  def waiting_to_start?
    started_at.nil?
  end

  # has game been started?
  def started?
    !(waiting_to_start?)
  end

  # has game been completed and archived?
  def paused?
    !(paused_at.nil?)
  end

  # is game currently running?
  def active?
    started? && !paused? && !finished?
  end

  # has game been completed and archived?
  def finished?
    !(finished_at.nil?)
  end

  # is this a multi-player game?
  def multiplayer?
    players.length > 1
  end

   # can players be added to this game?
  def can_add_new_player?
    waiting_to_start? && (players.length < MaxPlayers)
  end

  # list of players that can be added
  def player_add_list
    Player.all.delete_if {|player| players.include? player }
  end

  # adds player to new game -- returns player added if successful
  def add_new_player( profile )
    return false unless can_add_new_player?
    pl = Player.new
    pl.profile = profile
    self.players << pl
    save
  end

  # remove player from new game -- returns player if removed
  def remove_player( profile )
    pl = Player.find_by_profile_id_and_game_id( profile.id, self.id )
    pl.destroy! if pl
  end

  # get names of players
  def player_names
    players.map {|player| player.name }.join(' vs. ')
  end

  # returns the most recently found sets, regardless of player.
  # If :all is passed as a parameter, return all sets.
  def sets( num_most_recent = Game::ActivityLogSize )
    return [] unless (num_most_recent.is_a?(Integer) || num_most_recent == :all)
    all_sets = players.inject([]) {|s_arr, player| s_arr += player.threecardsets }
    return (num_most_recent == :all) ? all_sets.sort : all_sets.sort.slice(0,num_most_recent)
  end

  # return sum of all times to find individual sets
  def total_time
    sets(:all).inject(0) {|sum, set| sum += set.seconds_to_find }
  end

  def average_time
    (total_time / selection_count.to_f).round_with_precision 3
  end

  #--- Set Game logic ----#

  # returns an array-of-arrays where the inner array are matching sets of three Card objects,
  # or an empty array if no sets are found.
  def find_sets
    found_sets = []
    flat_field = field.flatten
    Game.each_cmb3(flat_field.length).each do |arr3|
      cards = arr3.map {|i| flat_field[i] }
      found_sets << cards if is_set?(*cards)
    end
    found_sets
  end

  # returns field position (as zero-position index) of each card within every three-card Set in the gamefield
  def find_set_card_positions
    card_positions = {}
    flat_field.each_with_index {|card, indx| card_positions[card.id] = indx }
    find_sets.map do |threecardset|
      threecardset.map {|card| card_positions[card.id] }
    end
  end

  # the basic algorithm for determining if three cards are a set: given three
  # card positions (within face-up array), iterate through each attribute
  # (color, shading, shape, number) and remove all instances where only a
  # match of 2 exists -- because a match of 2 means "not all the same,
  # and not all different."
  def is_set?( card1, card2, card3 )
    cardfaces = [card1.cardface, card2.cardface, card3.cardface]
    Cardface::ATTR.each do |attr|
      return false if num_different_attr( attr, cardfaces ) == 2
    end
    true
  end

  # the heart of the Setsolver game logic lies here.
  # This method handles new games, and all types of card submissions
  # (valid set, invalid set, wrong # of cards selected, etc. )
  def play_cards_from_field(player, indices)
    selection_cards = indices.map {|str_indx| flat_field[str_indx.to_i] }
    if (selection_cards.compact.length != 3)
      return {
        :state => :bad_move,
        :error => 'You did not select three cards.'
      }
    end
    found_set = make_set_selection(player, *selection_cards)
    unless found_set
      return {
        :state => :bad_move,
        :error => 'The three cards you selected are not a set.'
      }
    end
    set_count = fill_gamefield_with_sets.count
    if (set_count > 0)
      return get_game_state(found_set, set_count)
    end
    return {:state => :finished}
  end

  # return game state as object
  def get_game_state(found_set = nil, set_count = 0)
    fill_gamefield_with_sets if (set_count < 1)
    response = {
      :field => flat_field.map {|card| {:name => card.name, :image => card.img_path} },
      :cards_remaining => cards_remaining,
      :set_count => set_count,
      :scores => players.map {|plyr| {:score => plyr.score, :id => plyr.id} }
    }
    unless found_set.blank?
      response[:set] = {
        :created_at => formatted_date(found_set.created_at),
        :cards => found_set.cards.map {|card| {:name => card.name, :image => card.small_img_path} }
      }
      response[:set_found_by] = found_set.player.name
      response[:state] = :good_move
    end
    return response
  end

  # given an array of cardfaces and an attribute, finds out how many distinct
  # attribute types exist in the array for the attribute type passed in.
  def num_different_attr( attr, cardface_arr )
    res = cardface_arr.map {|card| card.send(attr) }
    res.uniq.length
  end

  # fills gamefield so that it contains at least 1 set, then return array of sets.
  # The timer gets refreshed when calling this function, if any cards changed.
  # Returns an empty array if no sets are found and the deck is empty (i.e. game finished)
  def fill_gamefield_with_sets
    num_empty_cards = FieldSize - flat_field.length
    dealt = (deck.deal num_empty_cards if num_empty_cards > 0)
    sets_found = find_sets
    until (sets_found.count > 0)  # assigning to temp variable "tmp_sets"
      if deck.all_dealt?
        finished_at = Time.now
        save!
        return []
      end
      dealt = deck.discard_and_replace 3
      sets_found = find_sets
    end
    sets_found
  end

private

  # evaluates player submission, and if set is valid:
  # set all three cards as claimed by player passed in, then
  # return the three-card set.
  def make_set_selection( plyr, card1, card2, card3 )
    return false unless is_set?(card1, card2, card3)
    # increment score
    plyr.score = (plyr.score || 0) + 1
    plyr.save
    # create new set
    newset = Threecardset.new :cards => [card1, card2, card3], :player => plyr
    newset if newset.save!
  end

  # pause game
  def pause
    self.paused_at = Time.now
    self.resumed_at = nil
    save
  end

  # resume game
  def resume_play
    self.paused_at = nil
    self.resumed_at = Time.now
    save
  end

  # mark game as finished
  def finish
    self.finished_at = Time.now
    save
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  include ApplicationHelper

    #------ Game resource methods ----#

    # GET /games/1
    # GET /games/1.json
    def show
      get_game
      respond_to do |format|
        format.html { redirect_to(archive_url) if @game.finished? }
        format.json  { render :json => @game }
      end
    end

    # GET /games/new
    # GET /games/new.json
    def new
      current_user
      @game = Game.new
      respond_to do |format|
        format.html # new.html.erb
        format.json  { render :json => @game }
      end
    end

    # POST /games
    # POST /games.json
    def create
      current_user
      # create game and save
      @game = Game.new(game_params)
      respond_to do |format|
        # creating new game, and new association between selected player and game
        if @game.add_new_player(@current_profile) && @game.save
          flash[:notice] = 'Game was successfully created.'
          format.html { redirect_to(game_url(@game)) }
          format.json  { render :json => @game, :status => :created, :location => @game }
        else
          format.html { render :action => "new" }
          format.json  { render :json => @game.errors, :status => :unprocessable_entity }
        end
      end
    end

    # PUT /games/1
    # PUT /games/1.json
    def update
      get_game
      respond_to do |format|
        if @game.update_attributes(game_params)
          flash[:notice] = 'Game was successfully updated.'
          format.html { redirect_to(@game) }
          format.json  { head :ok }
        else
          format.html { render :action => "edit" }
          format.json  { render :json => @game.errors, :status => :unprocessable_entity }
        end
      end
    end

    # DELETE /games/1
    # DELETE /games/1.json
    def destroy
      # delete Score first, then Game
      get_game
      @game.players.each {|p| p.destroy }
      @game.destroy

      respond_to do |format|
        format.html { redirect_to(games_url) }
        format.json  { head :ok }
      end
    end

  #------ my controller methods ----#

  # GET /games/1/play
  # GET /games/1/play.json
  # plays submitted Set cards if submit button was clicked, then refreshes board
  def play
    get_game
    @game.start if @game.waiting_to_start?
    if @game.fill_gamefield_with_sets.blank?
      redirect_to :action => 'archive'
    else
      render :action => 'play'
    end
  end

  # GET /games/1/archive
  # GET /games/1/archive.json
  # plays submitted Set cards if submit button was clicked, then refreshes board
  def archive
    get_game
    respond_to do |format|
      format.html # new.html.erb
      format.json  { render :json => @game }
    end
  end

    # PUT /games/1/play_cards.json
    # the heart of the Setsolver game logic lies here.
    # This method handles new games, and all types of card submissions
    # (valid set, invalid set, wrong # of cards selected, etc. )
    def play_cards
      get_game
      selection = params[:cards].split(",")
      render :json => @game.play_cards_from_field(@current_player, selection)
    end

    # GET /games/1/field.json
    # Ajax refresh routine for auto-selection
    def get_game_state
      get_game
      render :json => @game.get_game_state
    end

    def howtoplay
      respond_to do |format|
        format.html {  }
        format.json  { head :ok }
      end
    end

    def archives
      respond_to do |format|
        format.html {  }
        format.json  { head :ok }
      end
    end

  protected

    def not_found
      flash[:error] = "Game ##{params[:id]} does not exist."
      redirect_to games_url
    end

    def user_not_playing_game
      flash[:error] = "You cannot play game ##{params[:id]}."
      redirect_to games_url
    end

    def invalid_game_state
      flash[:error] = "Game ##{params[:id]} must be either Waiting, Active, or Finished. " +
  	            "Contact the Setsolver developer for further assistance."
      redirect_to games_url
    end

  private

    # get Game object if a game ID was passed in.
    # This routine throws a UserNotPlayingGame error if the game ID passed in
    # is not being played by the current user.
    def get_game
      current_user if @current_user.blank?  # get user and profile
      @set_count = 0
      @found_set = nil
      if (params[:id])
        @game = Game.find(params[:id])
        @current_player = Player.find_by_profile_id_and_game_id(@current_profile.id, @game.id)
      end
      true
    end

    # get card numbers from params hash that takes the following form:
    # key = :card<number>, value = "SELECTED"
    # The array of card numbers is always in numerical order.
    def get_card_numbers
      cardparams = game_params.clone.delete_if do |k,v|
        (v.to_s != 'SELECTED') || (k.to_s !~ /^card[0-9]+$/)
      end
      nums = cardparams.map {|cardparam| cardparam.to_s.sub(/^card/,'').to_i }.sort
    end

    def game_params
      params.require(:game).permit(:name)
    end
end

app/helpers/games_helper.rb
module GamesHelper
  # renders wait text for when user submits three-card set.
  def wait_text
    str = 'Waiting for results... ' + image_tag('spinner.gif', :alt => 'spinner')
  end

  # prints three card set as miniature cards
  def render_threecard_set( tcs )
    return render_dummy_set if tcs.blank?
    cards = (tcs.is_a? Threecardset) ? tcs.cards : tcs
    cards.inject('') do |str,c|
      str += ' ' unless str.length == 0
      str += extra_small_setcard_img(c)
    end
  end

  # prints three card set as miniature cards, given cardface ID's
  def render_threecard_set_from_cardface_ids( *cf_ids )
    render_threecard_set( cf_ids.map {|id| Cardface.find(id) } )
  end

  # renders an extra-small Set card
  def extra_small_setcard_img( card )
    image_tag(card.small_img_path, :height => 45, :width => 30, :alt => card.to_s)
  end

  # renders an invisible dummy set
  def render_dummy_set
    str = ""
    3.times do |x|
      str += ' ' unless str.length == 0
      str += image_tag( 'cards/card_template.png' )
    end
    str
  end

  # create game number as link
  def game_desc_as_link( gm )
    link_to(gm.listing, game_path(gm))
  end

  # create game number as link
  def game_play_link( gm )
    if gm.waiting_to_start?
      link_to("Start playing!", play_path(gm), :class => 'mock-fb-button')
    elsif gm.active?
      link_to("Continue playing", play_path(gm), :class => 'mock-fb-button')
    elsif gm.finished?
      link_to("Game Archive", archive_path(gm), :class => 'mock-fb-button')
    else
      raise Exceptions::InvalidGameState
    end
  end

  # returns image HTML for a single card
  def card_image( card )
    image_tag(card.img_path, :height => 90, :width => 60, :alt => card.to_s)
  end

  def render_set_found_text( set )
    "<h5>#{formatted_date(set.created_at) if set}</h5> " +
    "<span class=\"setlisting-name\">#{set.player.name if set}</span> found a set: " +
    "<p class=\"setlisting\">#{render_threecard_set(set)}</p> "
  end

end

app/views/games/_gamefield.html.erb
<!--[form:game]-->

<div id="setboard_panel" class="setboard-panel">
  <h3>The deck has <span id="remaining"><%= number_noun_desc( @game.cards_remaining, 'card' ) %></span> remaining. </h3>
  <h3><span id="num_sets"><%= number_noun_desc( @set_count, 'set' ) %></span> can be found below: </h3>
  <div id="setboard" class="setboard" data-gameid="<%= @game.id %>">
    <% indx = 0 %>
    <% @game.field.each_with_index do |row, row_i| %>
      <ul id="row<%= row_i %>" class="setboard-row">
      <% row.each_with_index do |c,col_i| %>
        <li id="c_card<%= indx.to_s %>" class="setboard-cell"><%= check_box_tag(('card' + indx.to_s), 'SELECTED', false) %><%= card_image c %></li>
        <% indx += 1 %>
      <% end %>
      </ul>
    <% end %>
  </div>
</div>

app/views/games/_rightpanel.html.erb
<!--[form:game]-->

<div id="right_panel" class="right-panel">
  <div id="score_panel" class="score-panel">
    <h1>Game Score</h1>
    <ul id="score_listing" class="score-listing">
    <% @game.players.each do |player| %>
      <li>(Pic Here)
          <%= player.name %>:
          <span id="gamescore_<%= player.id %>"><%= player.score %></span></li>
    <% end %>
    </ul>
  </div>
  <div id="activity_panel" class="activity-panel">
    <h1>Game Activity</h1>
    <ul id="set_records" class="set-records">
    <% @game.sets.each do |set| %>
      <li><%= render_set_found_text(set).html_safe %></li>
    <% end %>
    <% if @game.selection_count == 0 %>
      <li class="dummy-first-node"><%= render_set_found_text(nil).html_safe %></li>
    <% end %>
    </ul>
  </div>
</div>

app/views/games/_sets_selected.html.erb
<% game.players.sort.each do |player| %>
  <div class="sets-selected">
  <h2><%= game.name %></h2>
  <ol id="archive_<%= player.name.underscore.sub(/\s/,"_") %>" style="text-align:left;">
    <% player.threecardsets.each_with_index do |set,i| %>
      <li><%= render_threecard_set(set).html_safe %></li>
    <% end %>
  </ol>
  </div>
<% end %>

app/views/games/archive.html.erb
<h1 class="setsolver">Game Archive: <%=@game.name %></h1>
<% if @game.finished? %>
  <p><b>Game started:</b> <%= h @game.started_at %> </p>
  <p><b>Game completed:</b> <%= h @game.finished_at %> </p>
  <p id="buttons">
    <%= link_to 'Back to Games', games_path, :class => "mock-fb-button" %>
  </p>
  <%= render :partial => 'sets_selected' %>
<% else %>
  <p>No archive data exists for this game.</p>
  <p><%= link_to '[ << Back to Game ]', game_path, :class => "mock-fb-button" %></p>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game <%= @game.title %></h1>

<% if @current_profile %>
  <% form_for(@game) do |f| %>
    <p>
      <b>Selection Count:</b>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.submit 'Edit Game', :class => "fb-button" %>
      <%= link_to 'Back', games_path, :class => "mock-fb-button" %>
    </p>
  <% end %>
<% end %>

app/views/games/howtoplay.html.erb
<h1>How To Play Setsolver</h1>
Setsolver is a Facebook interactive version of the SET&dagger; card game, where the object of the
game is to find "sets" of three cards with matching characteristics.  Each card has four characteristics:
<ul>
<li><strong>number</strong>: the number of shapes on the card.  Every card will have
    <strong>1</strong>, <strong>2</strong>, or <strong>3</strong> shapes, and multiple shapes will
    always be identical to one another.</li>
<li><strong>shape</strong>: the type of shape displayed on the card.  These shapes will always be
    either <strong>oval</strong>, <strong>diamond</strong>, or <strong>squiggle</strong>.
<li><strong>color</strong>: the color of the shapes (<strong>red</strong>, <strong>green</strong>,
    or <strong>purple</strong>).</li>
<li><strong>shading</strong>: how darkly shaded are the shapes? Shapes can be either
    <strong>outlined</strong>, <strong>filled</strong> solid, or <strong>shaded</strong> with line patterns.</li>
</ul>
<p>Think about normal playing cards -- they have two characteristics (number and suit) and the cards
themselves are made up of every combination of number and suit.  A deck of SET cards similarly has
every combination of the four characteristics above, for a result of 3x3x3x3 (or 81) cards.  Here are a
few examples: </p>

<%= print_example_cards %>

<h2>Finding a Set</h2>

<p>Now that you are familiar with the cards, we move on to the object of the game: finding three-card
sets. A collection of three cards is considered a set if <strong>all four of their characteristics are
either all alike or all different</strong>.   Three purple cards would count as "all alike" in its
color characteristic, and if these cards were one red, one green, and one purple this would count as
"all different".  If all three other characteristics (number, shading, and shape) fit this patterns
then you have a Set.  If one characteristic fails in being all different or all the same (such as
two purples and a green) then you don't have a Set, regardless of the other three characteristics.</p>

<h2>Examples of Sets</h2>

<h3>Here are some examples of three-card combinations that are Sets:</h3>

<p><%= render_threecard_set_from_cardface_ids(4,31,58) %>: This is a Set because the colors are
all green, the shadings are all filled, the shapes are all diamonds, but the numbers are all
different (1 diamond, 2 diamond, and 3 diamonds).  Sets like this with three common
characteristics are the easiest to find.</p>

<p><%= render_threecard_set_from_cardface_ids(12,13,17) %>: This is a Set because the colors are
all red, only one shape exists in each card, and yet the shadings and shapes are all different
for each card.</p>

<p><%= render_threecard_set_from_cardface_ids(2,40,81) %>: This Set is hard to identify because no
characteristics are alike in any of the cards, but nevertheless it is a Set.  If no obvious Sets
can be found at first, there's a good chance that a three-card Set exists with different colors,
different numbers, different shapes, and different shadings.</p>

<h3>...and here are some three-card examples of non-Sets:</h3>

<p><%= render_threecard_set_from_cardface_ids(4,32,58) %>: This may look like a Set at first glance
because of the similarity to the first example above.  However, the shapes are not all same or all
different (diamond, squiggle, diamond), and as such this is not a Set.</p>

<p><%= render_threecard_set_from_cardface_ids(65,60,73) %>: Another deceptive non-Set: the numbers
and colors match up, but the shadings do not. (2 shaded, 1 filled).</p>

app/views/games/new.html.erb
<%= form_for @game do |f| %>
  <p>
    <b>Enter a name for your game:</b>
    <%= f.text_field :name, :value => default_game_name %>
  </p>

  <p>
    <%= f.submit 'Create New Game' %>
  </p>
<% end %>
 d

app/views/games/play.html.erb
<% content_for :html_head do %>
  <%= stylesheet_link_tag "play" %>
  <%= javascript_include_tag "play" %>
<% end %>

<h1 class="setsolver">Game <%= @game.title %></h1>
<% if @game.active? %>
  <p id="submitbar" style="display:none;">Submitting set; waiting for response <img src="/spinner.gif"></p>
  <div id="body">
    <%= render :partial => 'gamefield' %>
    <%= render :partial => 'rightpanel' %>
</div>
<% else %>
  <p>This game has not yet started.</p>
  <p><%= link_to 'Back to Game', game_path, :class => "mock-fb-button" %></p>
<% end %>

<p />
<p>
<%= link_to 'Exit Game', games_path, :class => "mock-fb-button" %>
</p>

app/views/games/show.html.erb
<p>
  <b><%= @game.listing %>  (<%= @game.player_names %>)</b>
</p>

<% if @game.active? %>
  <p><b>Game started:</b> <%= h @game.started_at %> </p>
  <p id="buttons">
    <%= link_to 'Continue Playing', play_path(@game), :class => "mock-fb-button" %>
    <%= link_to 'Back', games_path, :class => "mock-fb-button" %>
  </p>
  <%= render :partial => 'sets_selected' %>
<% elsif !(@game.started?) %>
  <p>Game not yet started. Press the "Start Game" button to start playing:</p>
  <p id="buttons">
    <%= link_to 'Start Playing!', play_path(@game), :class => "mock-fb-button" %>
    <%= link_to 'Back', games_path, :class => "mock-fb-button" %>
  </p>
<% end %>